name: mealie
title: Mealie
license: GPL-3.0
website: https://mealie.io/
donation: https://github.com/sponsors/danbishop
source-code: https://github.com/mealie-recipes/mealie
issues: https://github.com/danbishop/mealie/issues
contact: d@nbishop.uk
base: core24
platforms:
  amd64:
  arm64:
adopt-info: backend
summary: Self-hosted recipe manager and meal planner
description: |
  Mealie is a self-hosted recipe manager and meal planner.
  This snap runs on port 9925 by default. This can be changed with:

  `sudo snap set mealie port=9925`

  You can also configure the base URL with:

  `sudo snap set mealie base-url=http://my-proxy-address.domain.tld`

grade: stable
confinement: strict

apps:
  mealie:
    command: bin/run.sh
    daemon: simple
    install-mode: enable
    plugs: [network, network-bind]
    environment:
      DATA_DIR: $SNAP_COMMON/data
      STATIC_FILES: "$SNAP/frontend"
      PRODUCTION: "true"
      TESTING: "false"

parts:
  frontend:
    plugin: npm
    source: https://github.com/mealie-recipes/mealie.git
    source-subdir: frontend
    override-pull: |
      craftctl default
      VERSION=$(git describe --tags --abbrev=0 2>/dev/null)
      git checkout $VERSION
    build-snaps:
      # use Node.js Snap during the build-time only
      - node/24/stable
    build-packages:
      - curl
      - gcc
      - g++
      - make
    override-build: |
      # Set proxies so that launchpad builds work
      if [ -n "${http_proxy:-}" ]; then
        export YARN_HTTP_PROXY="${http_proxy:-}"
        export YARN_HTTPS_PROXY="${http_proxy:-}"
      fi
      cd $CRAFT_PART_SRC/frontend
      yarn install --prefer-offline --frozen-lockfile --non-interactive --production=false
      yarn generate

      # Copy compiled frontend to prime
      cp -a ${CRAFT_PART_SRC}/frontend/dist/ ${SNAPCRAFT_PRIME}/frontend
      craftctl default

  backend:
    plugin: python
    after:
      - frontend
    source: https://github.com/mealie-recipes/mealie.git
    override-pull: |
      craftctl default
      VERSION=$(git describe --tags --abbrev=0 2>/dev/null)
      git checkout $VERSION
      craftctl set version="$VERSION"
    python-packages:
      - uvicorn
      - gunicorn
    stage-packages:
      - libpq-dev
      - libsqlite3-dev
      - libldap2
      - libsasl2-2
    build-packages:
      - libldap2-dev
      - libsasl2-dev
      - libssl-dev
      - python3
      - python3-dev
      - gcc
      - python3-pip
      - python3-venv
    override-build: |      
      # Install local dependencies
      pip install --break-system-packages .
      
      # Build the part
      pip install --break-system-packages uv
      uv build --out-dir $CRAFT_PART_INSTALL/
      uv export --no-editable --no-emit-project --extra pgsql --format requirements-txt --output-file $CRAFT_PART_INSTALL/requirements.txt \
      && MEALIE_VERSION=$(python3 -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])") \
      && echo "mealie[pgsql]==${MEALIE_VERSION} \\" >> $CRAFT_PART_INSTALL/requirements.txt \
      && pip hash $CRAFT_PART_INSTALL/mealie-${MEALIE_VERSION}-py3-none-any.whl | tail -n1 | tr -d '\n' >> $CRAFT_PART_INSTALL/requirements.txt \
      && echo " \\" >> requirements.txt \
      && pip hash $CRAFT_PART_INSTALL/mealie-${MEALIE_VERSION}.tar.gz | tail -n1 >> $CRAFT_PART_INSTALL/requirements.txt
      craftctl default

      # install nltk data for the ingredient parser
      mkdir -p $CRAFT_PART_INSTALL/nltk_data/
      python -m nltk.downloader -d $CRAFT_PART_INSTALL/nltk_data/ averaged_perceptron_tagger_eng

  config:
    plugin: dump
    source: .
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin

      # Launch Script
      cat <<EOF > $CRAFT_PART_INSTALL/bin/run.sh
      #!/bin/bash
      # Source the file created by the configure hook if it exists
      if [ -f "\$SNAP_COMMON/config.env" ]; then
        . "\$SNAP_COMMON/config.env"
      fi
      exec mealie
      EOF

      chmod +x $CRAFT_PART_INSTALL/bin/*.sh

lint:
  ignore:
    - library